# Generated by Django 4.0.6 on 2022-07-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ratings', models.FloatField()),
                ('contactNo', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('bloodGroup', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('mobileNo', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('mobileNo', models.BigIntegerField()),
                ('morningTime', models.DateTimeField()),
                ('eveningTime', models.DateTimeField()),
                ('experience', models.FloatField()),
                ('password', models.CharField(max_length=100)),
                ('hospitalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
