# Generated by Django 4.0.6 on 2022-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='eveningTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='morningTime',
            field=models.TimeField(),
        ),
    ]
