# Generated by Django 4.0.6 on 2022-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_eveningtime_alter_doctor_morningtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='eveningTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='morningTime',
            field=models.CharField(max_length=100),
        ),
    ]
