# Generated by Django 4.0.6 on 2022-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='eveningTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='morningTime',
            field=models.TimeField(),
        ),
    ]
